[package]
name = "AnimeSwapV1"
version = "0.4.0"

[dependencies]
AptosFramework = { git = "https://github.com/aptos-labs/aptos-core.git", subdir = "aptos-move/framework/aptos-framework/", rev = "83641d3f083762f31700060e5e95fbb1cbc28bf0" }
LPCoin = { local= "../LPCoin" }
LPResourceAccount = { local= "../LPResourceAccount" }
TestCoin = { local= "../TestCoin" }
U256 = { local= "../u256" }
UQ64x64 = { local= "../uq64x64" }

[addresses]
SwapDeployer = "0x16fe2df00ea7dde4a63409201f7f4e536bde7bb7335526a35d05111e68aa322c"
ResourceAccountDeployer = "0xe73ee18380b91e37906a728540d2c8ac7848231a26b99ee5631351b3543d7cf2"
